### ISSUE TITLE
Change the default

### ISSUE THREAD

**Issue by ryanhiebert** [aspiredu/django-safemigrate#38]
I'm in the process of adding safemigrate to an existing django project that has lots of migrations already. When I chose the default to be after deploy, I felt that this was the safest default, but I don't think I was correct in that judgement, and when I chose that default there was no `always` option. I'm convinced now that there is no "safe" default. That's the reason for this package in the first place.

Ideally, we'd be able to force that all migrations have the `safe` property explicitly declared, but that's not reasonable to do with third-party applications, so we'd need a way to reliably indicate which apps are under our control. That might be a little more than we want to chew on, I think we'd probably have to have some kind of a setting for that purpose, but even that sounds brittle and annoying to maintain.

At this point, I feel like the most appropriate default would be to behave exactly as Django would for unmarked migrations, and change the default to `always`. This would be a **breaking change**, but I'm not sure how significant of a breaking change I feel that it is. If we're worried about it breaking existing code in challenging ways, we could implement a setting, but at least for my uses this setting only matters until the migration gets deployed on all production systems, so it has an automatic expiring effect. I don't really _care_ what the early migrations have set, since probably the only place I'll be running them anymore is in CI where I skip `safemigrate` and just use `migrate` so that there won't be anything blocking.

**Comment by ryanhiebert** [comment]
Welp, I took a look at the release notes and I was wrong. I changed the default at the same time I added the `always` option, so I did have that option at the time. I'm not sure how widespread use of this package is, it still seems fairly low usage, so I'm inclined to go ahead and just make the change.

**Comment by tim-schilling** [comment]
I'm not sure I agree with present Ryan. I think Past Ryan had some good thoughts. However, I do see how your particular project could benefit from a different default value. It's probably worth making it a customizable default to allow each project to make the best decision possible and potentially even change it for specific deployments.

**Comment by agorka-contractsafe** [comment]
>  It's probably worth making it a customizable default to allow each project to make the best decision possible and potentially even change it for specific deployments.

Full disclosure, I work with @ryanhiebert. I like the idea of overriding a default through a setting. I think our organization would benefit from something like that, since there's some muscle memory to expecting migrations to run before a deploy and it could be easy to miss setting the attribute as the team gets used to it. We also appear to trend toward needing them run before rather than after. So if I were configuring it for our project, I would likely set it to always or before a deployment.

**Comment by ryanhiebert** [comment]
I didn’t expect you to write it ;-) pretty sure I’m still a maintainer on this repo. I intend to get to it today, but it might end up early next week.

**Comment by ryanhiebert** [comment]
I went back to the original discussion (https://github.com/aspiredu/django-safemigrate/issues/5) to see why we settled on the default we did. It was insightful.

btw, Tim, you were right, `after_deploy` and `before_deploy` are enough simpler that it's worthwhile to have the longer names. I'm glad you dragged me into calling them that, it was totally the right choice.

A use-case implied in that issue is to block sequential after_deploy migrations, as this library used to do with sequential `safe = False` migrations. This can be handled by adding an empty `before_deploy` migration between them, so I think we're OK there. (not that anyone cared, I just thought of that and wanted to write it down somewhere).

I love the idea of the pre-commit hook (#39). In fact, I think that the usage of a commit hook would alleviate all the concerns I have about having the default be `Safe.always`. `always` would be used by libraries, so that they would get standard Django migrate behavior by default, and the local repository would not. I'd be good with adding a default to do the same thing as the hook at safemigrate runtime, but I don't suspect I'd ever actually get around to writing it.

I think especially with the ability to have a pre-commit hook, the utility of the sort-of-conservative default of `Safe.after_deploy` becomes significantly reduced, and I'd rather have the default benefit new users of the library to incrementally and painlessly adopt it. Really, I see the `Safe.after_deploy` default as an easier-to-implement substitute for throwing errors when the safe property is left out.

**Comment by ryanhiebert** [comment]
As I mentioned in my write-up on #54, I still think that always is the optimal default, and I think that now is the right time to reconsider it. I think that adding the delay to after_deploy migrations helps expose that, and the default will likely matter most for libraries and django itself where we don't have the ability to require them to have the safe property. Other tools like the pre-commit hook are better for enforcing the safe property is set on migrations.

**Comment by tim-schilling** [comment]
Fair enough. I do rely on precommit to catch it at this point.
